services:
  postgres:
    image: postgres:16
    container_name: wow_postgres
    environment:
      POSTGRES_USER: wow_user
      POSTGRES_PASSWORD: wow_password
      POSTGRES_DB: wow_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
